# Generated by Django 4.2.17 on 2025-02-08 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersecurityquestion",
            name="custom_question",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("system", "System Message"),
                    ("task", "Task Notification"),
                    ("security", "Security Alert"),
                    ("group", "Group Message"),
                    ("gambling", "Gambling Update"),
                    ("notification", "Notification"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usersecurityquestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersecurityquestion", unique_together={("user", "question")},
        ),
        migrations.AlterModelTable(name="securityquestion", table=None,),
        migrations.AlterModelTable(name="usersecurityquestion", table=None,),
        migrations.CreateModel(
            name="UserIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("is_first_ip", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used"],
                "unique_together": {("user", "ip_address")},
            },
        ),
    ]
