# Generated by Django 4.2.17 on 2025-02-09 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usersecurityquestion_custom_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="securityquestion", name="is_custom",),
        migrations.RemoveField(model_name="securityquestion", name="question_text",),
        migrations.AddField(
            model_name="securityquestion",
            name="answer",
            field=models.CharField(default="Not set", max_length=255),
        ),
        migrations.AddField(
            model_name="securityquestion",
            name="question",
            field=models.CharField(
                default="What is your mother's maiden name?", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="securityquestion",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
