# Generated by Django 4.2.17 on 2025-02-09 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_useripaddress"),
    ]

    operations = [
        migrations.RemoveField(model_name="securityquestion", name="created_at",),
        migrations.RemoveField(model_name="useripaddress", name="is_first_ip",),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="useripaddress",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="securityquestion",
            name="answer",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="securityquestion",
            name="question",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="securityquestion",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useripaddress",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="useripaddress",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
