# Generated by Django 4.2.17 on 2025-02-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_securityquestion_created_at_and_more"),
        ("users", "add_security_questions"),
    ]

    operations = []
