# Generated by Django 4.2.17 on 2025-04-04 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gambling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitedgambler",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="gamblingtransaction",
            name="bet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="gambling.gamblingbet",
            ),
        ),
        migrations.AddField(
            model_name="gamblingbet",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="gambling.gamblinggame",
            ),
        ),
        migrations.AddField(
            model_name="gamblingbet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gambling_bets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invitedgambler", unique_together={("game", "user")},
        ),
    ]
