# Generated by Django 4.2.17 on 2025-02-27 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0002_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="withdrawalrequest", name="account",),
        migrations.RemoveField(model_name="withdrawalrequest", name="admin_notes",),
        migrations.RemoveField(model_name="withdrawalrequest", name="completed_at",),
        migrations.RemoveField(model_name="withdrawalrequest", name="fee",),
        migrations.RemoveField(
            model_name="withdrawalrequest", name="transaction_hash",
        ),
        migrations.RemoveField(model_name="withdrawalrequest", name="updated_at",),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="network",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin"),
                    ("ETH", "Ethereum"),
                    ("USDT", "USDT-TRC20"),
                    ("BSC", "Binance Smart Chain"),
                ],
                max_length=10,
            ),
        ),
    ]
